name: Publish to github pages
run-name: ${{ github.actor }} is publishing to github pages
on:
  push:
    branches:
      - master
      - main

env:
  PUG_OUTPUT: ./.public

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install pugjs cli
        run: npm install pug-cli -g
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build using pug
        run: pug index.pug # --out $PUG_OUTPUT
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: . #${{ env.PUG_OUTPUT }}

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
